import './HomePage.css';

interface HomePageProps {
  onGoToLibrary: () => void;
  onCreateNew: () => void;
}

export default function HomePage({ onGoToLibrary, onCreateNew }: HomePageProps) {
  return (
    <div className="home">
      {/* Animated background blobs */}
      <div className="home__bg">
        <div className="home__blob home__blob--1" />
        <div className="home__blob home__blob--2" />
        <div className="home__blob home__blob--3" />
      </div>

      {/* Main content */}
      <div className="home__content">
        {/* Theater masks logo */}
        <div className="home__logo" aria-hidden="true">🎭</div>

        {/* Brand */}
        <h1 className="home__brand">
          <span className="home__brand-accent">A</span>UDITORIUM
        </h1>
        <p className="home__tagline">AI Audio Drama Generation</p>

        {/* Hero text */}
        <h2 className="home__heading">
          Stories that come alive<br />through sound
        </h2>
        <p className="home__subheading">
          Transform any story into a fully produced audio drama with distinct character voices,
          cinematic sound effects, and original music — all generated by AI.
        </p>

        {/* CTA buttons */}
        <div className="home__actions">
          <button
            className="home__btn home__btn--primary"
            onClick={onCreateNew}
            type="button"
          >
            ✦ Create New Drama
          </button>
          <button
            className="home__btn home__btn--secondary"
            onClick={onGoToLibrary}
            type="button"
          >
            Browse Library →
          </button>
        </div>
      </div>

      {/* Footer */}
      <div className="home__footer">
        Built with <a href="https://elevenlabs.io" target="_blank" rel="noopener">ElevenLabs</a> · <a href="https://kiro.dev" target="_blank" rel="noopener">AWS Kiro</a>
      </div>
    </div>
  );
}
